branch-defaults:
  main:
    environment: lmdt-interocio
    group_suffix: null
global:
  application_name: LMDT-SHIELD-Interocio
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 17 running on 64bit Amazon Linux 2023
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
